bunsess/urls.py
from django.urls import path, include
from  . import views
from rest_framework import routers
from .views import ExportConventionCSVView, ExportSitesCSVView
# Ici nous créons notre routeur
router = routers.SimpleRouter(trailing_slash=False)

#router.register(r'users', UserViewset, basename='users'),

app_name = "bunsess"

urlpatterns = [
    path("dashboard", views.dashboard, name="dashboard"),
    path("charts/", views.charts, name="charts"),
    path("rapportMort/", views.rapportMort, name="rapportMort"),
    path("boadConvention/", views.boadConvention, name="boadConvention"),
    path("guideAutorite/", views.guideAutorite, name="guideAutorite"),
    path("messages/", views.send_messages, name="messages"),
    path("messages_archives/", views.messages_archives, name="messages_archives"),
    path('api/', include((router.urls, 'app_name_bi'))),
    path('convention/export/csv/', ExportConventionCSVView.as_view(), name='export_conv_csv'),
    path('site/export/csv/', ExportSitesCSVView.as_view(), name='export_site_csv'),
]

sigips/urls.py
from django.contrib import admin
from django.urls import path, include
from  django.conf.urls.static import  static
from  django.conf import settings

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path('', include('technique.urls')),
    path('', include('commercial.urls')),
    path('', include('environnement.urls')),
    path('', include('authentication.urls')),
    path('', include('bunsess.urls')),
    path('api-auth/', include('rest_framework.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

technique/urls.py
from django.urls import path, include
from rest_framework import routers
from  . import views
from technique.views import *


router = routers.SimpleRouter()
router.register('sites', ComsitesViewset, basename='sites')
router.register('statut', StatutsitesViewset, basename='statut')
router.register('types', TypesitesViewset, basename='types')
router.register('regions', RegionsViewset, basename='regions')

urlpatterns = [
    # gestion site
    path('site', views.site, name='site'),
    path('webmapp', views.webmapp, name='webmapp'),
    path('api/', include(router.urls)),
    
    
    path('site/add', views.add_site, name='add_site'),
    path('site/edit/<int:id>', views.edit_site, name='edit_site'),
    path('site/delete/<int:id>', views.delete_site, name='delete_site'),
    #Url de la fiche d'enrolment
    path('enrolement', views.index, name='list_enrolement'),
    path('enrolement/api_data', views.get_api_enrolement, name='api_enrolement'),
    path('syn_detail/<int:identifiant>', views.syn_detail, name='syn_detail'),
    path('syn/<int:identifiant>', views.save_api_data_to_database, name='syn'),
    path('enrolement/add', views.add, name='add_enrolement'),
    path('enrolement/edit/<int:id>', views.edit, name='edit_enrolement'),
    path('enrolement/delete/<int:id>', views.delete, name='delete_enrolement'),
    path('carte', views.carte, name="carte"),
    
    #Url de la fiche de viste et guide autorite et rapport d'activité
    path('guide_autorite', views.index1, name='guide_fiche'),
    path('guide_autorite/add', views.add_guide, name='add_guide'),
    path('guide_autorite/edit/<int:id>', views.edit_guide, name='edit_guide'),
    path('guide_autorite/delete/<int:id>', views.delete_guide, name='delete_guide'),
    
    
    
    #Url de la fiche de viste et guide autorite et rapport d'activité
    path('visite', views.index2, name='visite_fiche'),
    path('visite/add', views.add_visite, name='add_visite'),
    path('visite/edit/<int:id>', views.edit_visite, name='edit_visite'),
    path('visite/delete/<int:id>', views.delete_visite, name='delete_visite'),
    
    
    
    #Url de la fiche de demande de convention
    path('convention/api_data', views.api_enrolement_conv, name='api_enrolement_conv'),
    path('convention/syn_detail/<int:identifiant>', views.syn_detail_conv, name='syn_detail_conv'),
    path('convention/syn/<int:identifiant>', views.save_api_data_to_database_conv, name='syn1'),
   
    path('convention', views.index3, name='convention'),
    path('instruire/<int:id>', views.instruire, name='instruire'),
    path('instruire_anull/<int:id>', views.instruire_anull, name='instruire_anull'),
    path('signature_anull/<int:id>', views.signature_anull, name='signature_anull'),
    path('signature_anull1/<int:id>', views.signature_anull1, name='signature_anull1'),
    path('signature/<int:id>', views.signature, name='signature'),
    path('signe/<int:id>', views.signe, name='signe'),
    path('convention/add', views.add_convention, name='add_convention'),
    path('convention/edit/<int:id>', views.edit_convention, name='edit_convention'),
    path('convention/edit1/<int:id>', views.edit_convention1, name='edit_convention1'),
    path('convention/edit2/<int:id>', views.edit_convention2, name='edit_convention2'),
    path('convention/delete/<int:id>', views.delete_convention, name='delete_convention'),
    
    
    
    #Url de la fiche de rapport d'accident et incident
    path('incident/api_data', views.get_api_accident, name='api_accident'),
    path('incident/syn_detail/<int:identifiant>', views.syn_detail_acc, name='syn_detail_acc'),
    path('incident/syn/<int:identifiant>', views.save_api_data_to_database_acc, name='syn2'),
   
    path('incident', views.index4, name='incident'),
    path('incident/add', views.add_incident, name='add_incident'),
    path('incident/edit/<int:id>', views.edit_incident, name='edit_incident'),
    path('incident/delete/<int:id>', views.delete_incident, name='delete_incident'),
    
    
    
     #Url de la fiche de rapport d'activité
    path('rapport/api_data', views.get_api_rapport, name='api_rapport'),
    path('rapport/syn_detail/<int:identifiant>', views.syn_detail_rapp, name='syn_detail_rapp'),
    path('rapport/syn/<int:identifiant>', views.save_api_data_to_database_rapp, name='syn3'),
   
    path('rapport', views.index5, name='rapport'),
    path('rapport/add', views.add_rapport, name='add_rapport'),
    path('rapport/edit/<int:id>', views.edit_rapport, name='edit_rapport'),
    path('rapport/delete/<int:id>', views.delete_rapport, name='delete_rapport'),

    
    
]

paramettre/models.py
from django.db import models
from django.contrib.gis.db import models
from django.core.exceptions import ValidationError
from django.db.models.signals import pre_save
from django.dispatch import receiver
from authentication.models import User


class Message(models.Model):
    phone_numbers = models.TextField()
    message = models.TextField()
    envoyeur = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    sent_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message sent at {self.sent_at}"




class Typautorisations(models.Model):
    libelle = models.CharField(max_length=1500, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    class Meta:
        verbose_name = "Typautorisations"
        verbose_name_plural = "Type d'autorisation"
        
    def __str__(self):
        return self.libelle


class Typdemandeurs(models.Model):
    libelle = models.CharField(max_length=1500, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    class Meta:
        verbose_name = "Typdemandeurs"
        verbose_name_plural = "Type demandeur"
        
    def __str__(self):
        return self.libelle


class Typenatureminerais(models.Model):
    libelle_type_nature_minerais = models.CharField(max_length=254, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    class Meta:
        verbose_name = "Typenatureminerais"
        verbose_name_plural = "Nature du minerai"
        
    def __str__(self):
        return self.libelle_type_nature_minerais


class Typenatureterrains(models.Model):
    libelle = models.CharField(max_length=1000, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

  

    class Meta:
        verbose_name = "Typenatureterrains"
        verbose_name_plural = "Nature terrain"
        
    def __str__(self):
        return self.libelle
    
    

class Typeorganisations(models.Model):
    libelle = models.CharField(max_length=1000, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

   
    class Meta:
        verbose_name = "Typeorganisations"
        verbose_name_plural = "Type d'organisation"
        
    def __str__(self):
        return self.libelle

class Typeproduitchimiques(models.Model):
    libelle = models.CharField(max_length=1000, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    class Meta:
        verbose_name = "Typeproduitchimiques"
        verbose_name_plural = "Type de produit chimique"
        
    def __str__(self):
        return self.libelle


class Typequipements(models.Model):
    libelle = models.CharField(max_length=1000, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    class Meta:
        verbose_name = "Typequipements"
        verbose_name_plural = "Type d'equipement"
        
    def __str__(self):
        return self.libelle



class Typesites(models.Model):
    libelle = models.CharField(max_length=1000, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

   
    class Meta:
        verbose_name = "Typesites"
        verbose_name_plural = "Type de site"
        
    def __str__(self):
        return self.libelle

class Typetaterrains(models.Model):
    libelle = models.CharField(max_length=1000, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    class Meta:
        verbose_name = "Typetaterrains"
        verbose_name_plural = "Type de terrain"
        
    def __str__(self):
        return self.libelle
    
    

class Regions(models.Model):
    numero = models.CharField(max_length=1000, blank=True, null=True)
    nomreg = models.CharField(max_length=1000, blank=True, null=True)
    cheflieu = models.CharField(max_length=1000, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    
    class Meta:
        verbose_name = "Regions"
        verbose_name_plural = "Region"
        
    def __str__(self):
        return self.nomreg

    


class Provinces(models.Model):
    numero = models.CharField(max_length=1000, blank=True, null=True)
    nomprov = models.CharField(max_length=500, blank=True, null=True)
    region = models.ForeignKey(Regions, blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    class Meta:
        verbose_name = "Provinces"
        verbose_name_plural = "Province"
        
    def __str__(self):
        return self.nomprov

class Statutsites(models.Model):
    libelle = models.CharField(max_length=1500, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

   
    class Meta:
        verbose_name = "Statut du sites"
        verbose_name_plural = "Statut du site"
        
    def __str__(self):
        return self.libelle
    


class Typecarte(models.Model):
    libelle = models.CharField(max_length=1000, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    class Meta:
        verbose_name = "Type de carte"
        verbose_name_plural = "Type de carte"
        
    def __str__(self):
        return self.libelle


   


class Burencadrements(models.Model):
    libelle = models.CharField(max_length=2000, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    class Meta:
        verbose_name = "Burencadrements"
        verbose_name_plural = "Bureau d'encadrement"
        
    def __str__(self):
        return self.libelle
    


class Cartartisants(models.Model):
    nom_prenom = models.CharField(max_length=2500, blank=True, null=True)
    type_carte = models.CharField(max_length=1500, blank=True, null=True)
    date_del = models.CharField(max_length=250, blank=True, null=True)
    date_exp = models.DateField(blank=True, null=True)
    localite = models.CharField(max_length=2500, blank=True, null=True)
    num_tel = models.CharField(max_length=1500, blank=True, null=True)
    num_quit = models.CharField(max_length=1500, blank=True, null=True)
    num_fich_eng = models.CharField(max_length=1500, blank=True, null=True)
    num_carte = models.CharField(max_length=1500, blank=True, null=True)
    observation = models.TextField(blank=True, null=True)
    nom_compt = models.CharField(max_length=2500, blank=True, null=True)
    date_heure = models.DateTimeField(blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

   


class Categories(models.Model):
    nom_categorie = models.CharField(max_length=500, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    
    class Meta:
        verbose_name = "Categories"
        verbose_name_plural = "Categorie"
        
    def __str__(self):
        return self.nom_categorie

    


class Communes(models.Model):
    nom_commune = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Nom de la commune")
    province = models.ForeignKey(Provinces, blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    
    class Meta:
        verbose_name = "Communes"
        verbose_name_plural = "Commune"
        
    def __str__(self):
        return self.nom_commune



class Comptoires(models.Model):
    nom_comptoire = models.CharField(max_length=1000)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    
    class Meta:
        verbose_name = "Comptoires"
        verbose_name_plural = "Comptoire"
        
    def __str__(self):
        return self.nom_comptoire

technique/models.py
from django.db import models

# Create your models here.

technique/templates/technique/site/add.html
{% extends 'base1.html' %}
{% load crispy_forms_tags %}
{% crispy example_form example_form.helper %}
{% load i18n %}
{% load static %}
{% block page_title %}
ajout sites
{% endblock %}

{% block extra_css %}
    <style xmlns="http://www.w3.org/1999/html">
    </style>
    <link rel="stylesheet" type="text/css" href={% static "css/bootstrap.min.css"%}>
    <link rel="stylesheet" type="text/css" href={% static "DataTables/datatables.min.css"%}/>
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
{% endblock extra_css  %}


{% comment %} {% load django_bootstrap5 %} {% endcomment %}


{% block content %}

<div class="container-fluid">
    <form method="post" class="card p-3 mt-5 border border-primary" enctype="multipart/form-data">
      
      {% csrf_token %}

      {{ form|crispy }}


      <div class="mt-4" style="width: 100p%;">
          
          <input type="submit" name="submit" value="Ajouter" class="btn btn-success" id="submit-id-submit" />
          <a style= "font-size: 15px;" href="{% url 'site' %}" type="button" class="btn btn-outline-danger mb-3 ms-2" style="wdith: 50px;" title="Close">
                <i class="fas fa-times"></i>
          </a>
      
      </div>
    </form>

</div>

{% endblock content %}



{% block srcipts %}


{% block extra_script %}

<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'DataTables/datatables.min.js' %}"></script>
<script src="{% static 'select2/dist/js/select2.min.js' %}"></script>
<link href="{% static 'select2/dist/css/select2.min.css' %}" rel="stylesheet" type="text/css">

<script>
  $("#id_region").select2({
   placeholder: "selectionner la region",
   allowClear: true
  });
  $("#id_province").select2({
   placeholder: "selectionner la province",
   allowClear: true
  });


  $("#id_commune").select2({
    placeholder: "selectionner la Commune",
    allowClear: true
   });
</script>

{% endblock extra_script %}


{% endblock srcipts %}

technique/templates/technique/site/carte.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>sonasp webmapping</title>

    <!-- Included -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}PAGO {% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <link rel="shortcut icon" href="{% static "/images/app_img/favicon.ico" %}" type="image/x-icon">
	<link rel="icon" href="{% static "/media/app_img/favicon.ico" %}" type="image/x-icon">
    <link rel="shortcut icon" href={% static "/images/app_img/pago.jpeg" %}>
    
    <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "/css/bootstrap-icons.css" %}" rel="stylesheet">
    <!-- fontAwesome-->
    <link href="{% static "/css/all.min.css" %}" rel="stylesheet">
    <!-- CSS Datatables -->
    <link href="{% static "/css/datatables.min.css" %}" rel="stylesheet">
    <!-- Leaflet -->
    <link href="{% static "/leaflet/leaflet.css" %}" rel="stylesheet">
  
    <link href="{% static "/webmapping/css/submenu.css" %}" rel="stylesheet">
    <!-- zoom in image-->
    <link href="{% static "/webmapping/css/zoom-in-image.css" %}" rel="stylesheet">
    <link href="{% static "/webmapping/css/L.Control.ZoomBox.css" %}" rel="stylesheet" />
    <link href="{% static "/webmapping/css/jquery.dataTables.min.css" %}" rel="stylesheet" />
    <!-- Custom css cloned -->
    <link href="{% static "/webmapping/css/clone.css" %}" rel="stylesheet" />




</head>

<body>
    <nav id="banner" class="navbar navbar-expand-md navbar-dark bg-success py-0 sticky-top align-items-center" style="z-index: 0;">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item d-flex align-items-center">
                    <a class="nav-link fa fa-right-to-bracket text-white" href="{% url 'bunsess:dashboard' %}"> &nbsp; <span class="text-white">CONEXION</span></a>
                </li>
             
            </ul>
        </div>
        <div class="mx-auto order-0">
          <img src="{% static 'media/app_img/img_avatar2.jpg' %}" class="img-fluid float-end" alt="Logo pago" style="width:8%;">
        </div>
       

    </nav>

    <div id='slide_menu'>
        <h3 class="text-center">
            SONASP
            <img src="{% static 'media/app_img/img_avatar2.jpg' %}" class="img-fluid float-end" alt="Logo pago" style="width:8%;">
        </h3>
        <div class="container mt-3">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="#types" role="tab" aria-controls="home" aria-selected="true">Types de sites</a>
                </li>
            </ul>
    
            <div class="tab-content  mt-2" id="myTabContent">
                <div class="tab-pane fade show active" id="types" role="tabpanel" aria-labelledby="home-tab">
                    <div id="typeFilters">
                        <!-- Les checkboxes seront ajoutées ici dynamiquement -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div id='map'>
        <div id="slide_button"  class="btn btn-primary d-flex align-items-center" type="button" onClick="toggleLeftPane(); event.stopPropagation();" value="">
            <i class="fas fa-eye"></i>
        </div>
        <div id="legend" onmouseover="map.dragging.disable(); map.touchZoom.disable();map.doubleClickZoom.disable(); map.scrollWheelZoom.disable()" 
                                  onmouseout="map.dragging.enable(); map.touchZoom.enable();map.doubleClickZoom.enable(); map.scrollWheelZoom.enable()"
                                  onclick="event.stopPropagation();">
            <label class="close" onclick="vCloseLegend();">&times;</label>
            <label>Légende</label>
            <br>
            <div id = "legend_container">
                <img id = "legend_image" src="">
            </div>
        </div>
    </div>


        <!-- Jquery -->
        <script src="{% static "/js/jquery-3.7.0.min.js" %}"></script>
        <script src="{% static "/webmapping/js/jquery.dataTables.min.js" %}"></script>
        <!-- Bootstrap -->
        <script src="{% static "/js/popper.min.js" %}"></script>
        <script src="{% static "/js/bootstrap.min.js" %}"></script>
        <!-- Leaflet -->
        <script src="{% static "/leaflet/leaflet.js" %}"></script>
        <!-- RBush: Leaflet Canvas Markers dependancy -->
        <script src="{% static "/leaflet/rbush.min.js" %}"></script>
        <!-- Leaflet Canvas Markers -->
        <script src="{% static "/leaflet/leaflet-markers-canvas.js" %}"></script>
        <!-- Leaflet Canvas Icon -->
        <script src="{% static "/leaflet/leaflet-canvasicon.js" %}"></script>
        <!-- Leaflet ZoomBox -->
        <script src="{% static "/leaflet/L.Control.ZoomBox.min.js" %}"></script>
        <script src="{% static "/webmapping/js/clone.js" %}"></script>
</body>

</html>

technique/templates/technique/site/delete.html
<!-- Modal -->
<div class="modal fade" id="deletesiteModal{{result.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deletesiteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header bg-success text-white">
          <h4 class="modal-title fs-5" id="deletesiteModalLabel"><i class="fa fa-trash"></i> </h4>
          <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
      
          <h4 class="fw-bold text-danger">Voulez vous supprimer?</h4>
  
        </div>
        <div class="modal-footer">
            <a href="{% url 'delete_site'  result.id %}" class="btn btn-outline-danger btn-sm btn-modal">Valider</a>
        </div>
      </div>
    </div>
  </div>

technique/templates/technique/site/edit.html
{% extends 'base1.html' %}
{% load crispy_forms_tags %}
{% crispy example_form example_form.helper %}
{% load i18n %}
{% load static %}
{% block page_title %}
ajout sites
{% endblock %}

{% block extra_css %}
    <style xmlns="http://www.w3.org/1999/html">
    </style>
    <link rel="stylesheet" type="text/css" href={% static "css/bootstrap.min.css"%}>
    <link rel="stylesheet" type="text/css" href={% static "DataTables/datatables.min.css"%}/>
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
{% endblock extra_css  %}


{% comment %} {% load django_bootstrap5 %} {% endcomment %}


{% block content %}

<div class="container-fluid">
    <form method="post" class="card p-3 mt-5 border border-primary" enctype="multipart/form-data">
      
      {% csrf_token %}

      {{ form|crispy }}


      <div class="mt-4" style="width: 100p%;">
          
          <input type="submit" name="submit" value="Ajouter" class="btn btn-success" id="submit-id-submit" />
          <a style= "font-size: 15px;" href="{% url 'site' %}" type="button" class="btn btn-outline-danger mb-3 ms-2" style="wdith: 50px;" title="Close">
                <i class="fas fa-times"></i>
          </a>
      
      </div>
    </form>

</div>

{% endblock content %}



{% block srcipts %}


{% block extra_script %}

<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'DataTables/datatables.min.js' %}"></script>
<script src="{% static 'select2/dist/js/select2.min.js' %}"></script>
<link href="{% static 'select2/dist/css/select2.min.css' %}" rel="stylesheet" type="text/css">

<script>
  $("#id_region").select2({
   placeholder: "selectionner la region",
   allowClear: true
  });
  $("#id_province").select2({
   placeholder: "selectionner la province",
   allowClear: true
  });


  $("#id_commune").select2({
    placeholder: "selectionner la Commune",
    allowClear: true
   });
</script>

{% endblock extra_script %}


{% endblock srcipts %}